//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AulaFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEMONSTRATIVO
    {
        public Nullable<int> ID_GRU { get; set; }
        public string NOME_GRU { get; set; }
        public Nullable<int> ID_SUB_GRU { get; set; }
        public string NOME_SUB_GRU { get; set; }
        public Nullable<int> ID_CLA { get; set; }
        public string NOME_CLA { get; set; }
        public int ID_SEC { get; set; }
        public string NOME_SEC { get; set; }
        public string UNI_MED { get; set; }
        public int ID_PRO { get; set; }
        public string DESCRICAO_PRO { get; set; }
        public Nullable<decimal> SALDO_ANTERIOR { get; set; }
        public Nullable<decimal> SALDO_ANT_CUSTO { get; set; }
        public Nullable<decimal> ENTRADA_QTD { get; set; }
        public Nullable<decimal> ENTRADA_VL_UNIT { get; set; }
        public Nullable<decimal> SAIDA_QTD { get; set; }
        public Nullable<decimal> SAIDA_CM { get; set; }
        public Nullable<decimal> SALDO_QTD { get; set; }
        public Nullable<decimal> SALDO_CM { get; set; }
    }
}
