//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AulaFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORNECEDOR
    {
        public int ID_FOR { get; set; }
        public string FANTASIA { get; set; }
        public string CNPJ { get; set; }
        public string RESPONSAVEL { get; set; }
        public string INS_MUNICIPAL { get; set; }
        public string INS_ESTADUAL { get; set; }
        public string ENDERECO { get; set; }
        public string BAIRRO { get; set; }
        public string UF { get; set; }
        public string TELEFONE { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string CELULAR { get; set; }
    }
}
