//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AulaFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITENS_NOTA
    {
        public int ITEM_NUM { get; set; }
        public int ID_PRO { get; set; }
        public int ID_NOTA { get; set; }
        public int ID_SEC { get; set; }
        public Nullable<decimal> QTD_PRO { get; set; }
        public Nullable<decimal> PRE_UNIT { get; set; }
        public Nullable<decimal> TOTAL_ITEM { get; set; }
        public Nullable<decimal> EST_LIN { get; set; }
    }
}
